### PR TITLE
[SQL-250] UI no longer cares about HTML

### PR DESCRIPTION
**Pull request by cliffcaseyyet**
TODO: bump UI version after release.

### CODE REVIEW

**Comment by kelvinqian00** [comment]
SQLite CI is failing...

**Comment by kelvinqian00** [comment]
In addition, we'll need to update the env var docs to say that `LRSQL_ENABLE_STMT_HTML` will no longer affect the statement browser in UI. Right now this is the description:
> Whether or not HTML data is returned in the LRS HTTP response. If `false` disables HTML rendering even if `LRSQL_ENABLE_ADMIN_UI` is `true`. **In that case the UI will not display the Statement Browser feature.**
--


<br class="Apple-interchange-newline">

**Review by kelvinqian00 — APPROVED** [review]

**Review by kelvinqian00 — CHANGES_REQUESTED** [review]
Oh dear I missed a spot: https://github.com/yetanalytics/lrsql/blob/d967da8456be2df6fcf3243ea15ea1f706338e62/doc/endpoints.md?plain=1#L44

**Comment by cliffcaseyyet** [comment]
> Oh dear I missed a spot:
> 
> https://github.com/yetanalytics/lrsql/blob/d967da8456be2df6fcf3243ea15ea1f706338e62/doc/endpoints.md?plain=1#L44

https://github.com/yetanalytics/lrsql/pull/414/commits/2f4198cf77871f6cdd1091f2ee54fd4b9999d49d

**Review by kelvinqian00 — APPROVED** [review]

**Pull request merged**
