### PR TITLE
copyright updates 2023

### PR DESCRIPTION
**Pull request by cliffcaseyyet**

### CODE REVIEW

**Comment by kelvinqian00** [comment]
Forgot a spot: https://github.com/yetanalytics/lrsql/blob/66928f2f967329e292db77e89f656060d277df35/NOTICE#L2

**Comment by kelvinqian00** [comment]
Also should this be updated? It's just demonstration log output but if we want to be complete...
https://github.com/yetanalytics/lrsql/blob/056310c59bc169c3217073164a9ed78e7559378c/doc/oidc/auth0.md#L189

**Comment by cliffcaseyyet** [comment]
> Forgot a spot:
> 
> https://github.com/yetanalytics/lrsql/blob/66928f2f967329e292db77e89f656060d277df35/NOTICE#L2

done

**Comment by cliffcaseyyet** [comment]
> Also should this be updated? It's just demonstration log output but if we want to be complete...
> 
> https://github.com/yetanalytics/lrsql/blob/056310c59bc169c3217073164a9ed78e7559378c/doc/oidc/auth0.md#L189

this one is fine, its just sample log output.

**Review by kelvinqian00 — APPROVED** [review]

**Pull request merged**
