### PR TITLE
SQL-161 add unix socket support

### PR DESCRIPTION
**Pull request by milt**
[SQL-161] Per https://github.com/yetanalytics/lrsql/issues/235 we'd like to be able to support the use of unix sockets with [junixsocket](https://kohlschutter.github.io/junixsocket/dependency.html).

This PR adds junixsocket at version 2.6.1 and provides some documentation on usage.

[SQL-161]: https://yet.atlassian.net/browse/SQL-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kelvinqian00** [comment]
Is it possible to add a test for this?

**Comment by milt** [comment]
> Is it possible to add a test for this?

It would be possible to test using testcontainers + docker compose I suppose, but it's a lot of work to just test the underlying lib which is already tested.

**Comment by kelvinqian00** [comment]
> It would be possible to test using testcontainers + docker compose I suppose, but it's a lot of work to just test the underlying lib which is already tested.

Okay, even then it should be simple enough to test manually by passing in that JDBC URL, which I'm assuming you already did on your end.

**Comment by milt** [comment]
Yep, in the course of troubleshooting https://github.com/yetanalytics/lrsql/issues/235

**Review by kelvinqian00 — APPROVED** [review]

**Pull request merged**
